podcaster/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "podcaster"

urlpatterns = [
    path("", include("podcaster.routes.app")),
    path("podcasts/", include("podcaster.routes.podcasts")),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from project.constant import ROOT

urlpatterns = [
    path("admin/", admin.site.urls),

    path(ROOT, include("project.routes.app")),
    
    path("albums/", include("project.routes.albums")),  
    path("artists/", include("project.routes.artists")),
    path("playlists/", include("project.routes.playlists")),
    path("podcasts/", include("project.routes.podcasts")),

    path("podcaster/", include("podcaster.urls")),
]

podcaster/models.py
from django.db import models

# Create your models here.

podcaster/routes/podcasts.py
from django.urls import path
import podcaster.views.podcasts as podcasts

from podcaster.constant import ROOT
app_name = "podcasts"

urlpatterns = [
    path(ROOT, podcasts.index, name="index"),    
    path("<int:id>/", podcasts.view, name="view"),
    path("create/", podcasts.create, name="create"),
]

podcaster/views/podcasts.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request) -> HttpResponse:
    return render(request, "podcaster/pages/podcasts/index.html")

def view(request, id) -> HttpResponse:
    return render(request, "podcaster/pages/podcasts/view.html")

def create(request) -> HttpResponse:
    return render(request, "podcaster/pages/podcasts/create.html")

project/routes/albums.py
from django.urls import path
import project.views.albums as albums

from project.constant import ROOT
app_name = "albums"

urlpatterns = [
    path(ROOT, albums.index, name="index"),    
    path("<int:id>/", albums.view, name="view"),
]

project/routes/artists.py
from django.urls import path
import project.views.artists as artists

from project.constant import ROOT
app_name = "artists"

urlpatterns = [
    path(ROOT, artists.index, name="index"),
    path("<int:id>/", artists.view, name="view"),
]

project/routes/playlists.py
from django.urls import path
import project.views.playlists as playlists

from project.constant import ROOT
app_name = "playlists"

urlpatterns = [
    path(ROOT, playlists.index, name="index"),    
    path("create/", playlists.create, name="create"),
    path("<int:id>/", playlists.view, name="view"),
]

project/routes/podcasts.py
from django.urls import path
import project.views.podcasts as podcasts

from project.constant import ROOT
app_name = "podcasts"

urlpatterns = [
    path(ROOT, podcasts.index, name="index"),    
    path("<int:id>/", podcasts.view, name="view"),
]

project/views/albums.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request) -> HttpResponse:
    return render(request, "pages/albums/index.html")

def view(request, id) -> HttpResponse:
    return render(request, "pages/albums/view.html")

project/views/artists.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request) -> HttpResponse:
    return render(request, "pages/artists/index.html")

def view(request, id) -> HttpResponse:
    return render(request, "pages/artists/view.html")

project/views/playlists.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request) -> HttpResponse:
    return render(request, "pages/playlists/index.html")

def view(request, id) -> HttpResponse:
    return render(request, "pages/playlists/view.html")

def create(request) -> HttpResponse:
    return render(request, "pages/playlists/create.html")

project/views/podcasts.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request) -> HttpResponse:
    return render(request, "pages/podcasts/index.html")

def view(request, id) -> HttpResponse:
    return render(request, "pages/podcasts/view.html")

podcaster/templates/podcaster/partials/icon.html
<a href="{% url 'podcaster:app:dashboard' %}">
	<div class="flex space-x-2 items-center">
		<div class="h-8 w-8 rounded-xl bg-green-500 relative">
			<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="absolute h-5 w-5 top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-white">
				<path d="m12 8-9.04 9.06a2.82 2.82 0 1 0 3.98 3.98L16 12" />
				<circle cx="17" cy="7" r="5" />
			</svg>
		</div>

		<div class="font-bold">Podcaster App</div>
	</div>
</a>

templates/pages/albums/index.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block content %}
	<nav class="flex items-center justify-between mb-10">
		<div class="flex items-center space-x-2 text-sm text-gray-500">
			<a href="{% url 'app:dashboard' %}">Dashboard</a>
			<span>/</span>
			<a href="{% url 'albums:index' %}" class="text-indigo-500">Albums</a>
		</div>

		{% include 'partials/profile.html' %}
	</nav>

	<section id="featured" class="mb-10">
		<h2 class="font-semibold mb-4">Featured Albums</h2>

		<a href="{% url 'albums:view' '1' %}">
			<div class="w-full rounded-3xl overflow-hidden bg-orange-500 text-white grid lg:grid-cols-2 gap-10 items-center">
				<div class="flex flex-col space-y-4 p-10 order-1 lg:order-0">
					<span class="font-medium text-sm uppercase">Albums</span>
					<h1 class="text-5xl font-bold">Louder Than Bombs</h1>
					<p class="text-sm line-clamp-3">Louder Than Bombs is a compilation album by English rock band the Smiths, released as a double album in March 1987 by their American record company, Sire Records</p>
				</div>

				<div class="relative h-full aspect-[4/3] order-0 lg:order-1">
					<div id="overlay" class="absolute inset-0 w-full h-full bg-gradient-to-t lg:bg-gradient-to-r from-orange-500 to-orange-600/10"></div>
					<img src="{% static 'images/the-smiths.jpg' %}" class="h-full w-full object-cover" />
				</div>
			</div>
		</a>
	</section>

	<section id="albums" class="mb-10">
		<h2 class="font-semibold mb-6">Albums Recommendations</h2>

		<div class="grid gap-6 grid-cols-2 sm:grid-cols-3 md:grid-cols-4 xl:grid-cols-5">
			{% for i in '0123456789'|make_list %}
				<a href="{% url 'albums:view' i %}">
					<div class="flex flex-col justify-end bg-gray-100 rounded-xl overflow-hidden p-4 text-gray-500">
						<div class="w-full h-full aspect-square mb-4 overflow-hidden rounded-lg bg-white flex items-center justify-center">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-8 w-8">
								<circle cx="12" cy="12" r="10" />
								<path d="M6 12c0-1.7.7-3.2 1.8-4.2" />
								<circle cx="12" cy="12" r="2" />
								<path d="M18 12c0 1.7-.7 3.2-1.8 4.2" />
							</svg>
						</div>

						<h3 class="text-sm font-semibold">Louder Than Bombs</h3>
						<p class="text-sm line-clamp-2">Louder Than Bombs is a compilation album by English rock band the Smiths, released as a double album in March 1987 by their American record company, Sire Records</p>
					</div>
				</a>
			{% endfor %}
		</div>
	</section>
{% endblock %}

templates/pages/albums/view.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block content %}
	<nav class="flex items-center justify-between mb-10">
		<div class="flex items-center space-x-2 text-sm text-gray-500">
			<a href="{% url 'app:dashboard' %}">Dashboard</a>
			<span>/</span>
			<a href="{% url 'albums:index' %}">Albums</a>
			<span>/</span>
			<a href="{% url 'albums:view' '1' %}" class="text-indigo-500">The Smiths</a>
		</div>

		{% include 'partials/profile.html' %}
	</nav>

	<section id="featured" class="mb-10">
		<div class="w-full aspect-[3/1] relative overflow-hidden rounded-xl mb-10">
			<img src="{% static 'images/the-smiths.jpg' %}" class="h-full w-full object-cover" />
		</div>

		<div class="flex flex-col space-y-2 mb-6">
			<span class="font-medium text-sm text-indigo-500 uppercase">Albums</span>
			<h1 class="text-5xl font-bold">Louder Than Bombs</h1>
			<p class="text-sm text-gray-500">Louder Than Bombs is a compilation album by English rock band the Smiths, released as a double album in March 1987 by their American record company, Sire Records</p>
		</div>

		<div class="flex items-center space-x-4">
			<span class="px-4 py-2 rounded-full text-sm bg-gray-200 text-gray-500">10 Total Songs</span>
			<span class="px-4 py-2 rounded-full text-sm bg-gray-200 text-gray-500">32:00 Total Duration</span>
		</div>
	</section>

	<section id="songs" class="mb-10">
		<div class="flex items-center justify-between mb-4">
			<h2 class="font-semibold">Songs List</h2>

			<div class="flex items-center space-x-4">
				<button class="w-10 h-10 rounded-full bg-indigo-500 flex items-center justify-center group" title="Play All" role="button">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 text-white">
						<polygon points="6 3 20 12 6 21 6 3" />
					</svg>
					<span class="sr-only">Play All</span>
				</button>
				<button class="w-10 h-10 rounded-full bg-indigo-500 flex items-center justify-center" title="Add to Playlist" role="button">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 text-white">
						<path d="M11 12H3" />
						<path d="M16 6H3" />
						<path d="M16 18H3" />
						<path d="M18 9v6" />
						<path d="M21 12h-6" />
					</svg>
					<span class="sr-only">Add to Playlist</span>
				</button>
			</div>
		</div>

		<div class="w-full overflow-hidden border border-gray-200 rounded-xl">
			<table class="w-full text-sm text-gray-500 border-collapse">
				<thead>
					<tr class="bg-gray-100 [&>th]:px-4 [&>th]:py-3 [&>th]:text-left [&>th]:font-semibold">
						<th class="text-start w-20">Actions</th>
						<th class="text-start w-auto">Title</th>
						<th class="text-start w-1/5">Duration</th>
						<th class="text-start w-1/5">Album</th>
					</tr>
				</thead>
				<tbody>
					{% for i in '0123456789'|make_list %}
						<tr class="bg-white [&>td]:px-4 [&>td]:py-3 border-t border-gray-200">
							<td>
								{% include 'partials/action.html' %}
							</td>
							<td>
								<h3 class="text-sm font-semibold">The Smiths</h3>
								<p class="text-sm line-clamp-2">Heaven Knows I'm Miserable Now.</p>
							</td>
							<td>3:45</td>
							<td>Louder Than Bombs</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</section>
{% endblock %}

templates/pages/artists/index.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block content %}
	<nav class="flex items-center justify-between mb-10">
		<div class="flex items-center space-x-2 text-sm text-gray-500">
			<a href="{% url 'app:dashboard' %}">Dashboard</a>
			<span>/</span>
			<a href="{% url 'artists:index' %}" class="text-indigo-500">Artists</a>
		</div>

		{% include 'partials/profile.html' %}
	</nav>

	<section id="featured" class="mb-10">
		<h2 class="font-semibold mb-4">Featured Artists</h2>

		<a href="{% url 'artists:view' '1' %}">
			<div class="w-full rounded-3xl overflow-hidden bg-yellow-500 text-white grid lg:grid-cols-2 gap-10 items-center">
				<div class="flex flex-col space-y-4 p-10 order-1 lg:order-0">
					<span class="font-medium text-sm uppercase">Artists</span>
					<h1 class="text-5xl font-bold">Nirvana</h1>
					<p class="text-sm line-clamp-3">Nirvana was an American rock band formed in Aberdeen, Washington, in 1987. Founded by lead singer and guitarist Kurt Cobain and bassist Krist Novoselic, the band went through a succession of drummers, most notably Chad Channing, before recruiting Dave Grohl in 1990.</p>
				</div>

				<div class="relative h-full aspect-[4/3] order-0 lg:order-1">
					<div id="overlay" class="absolute inset-0 w-full h-full bg-gradient-to-t lg:bg-gradient-to-r from-yellow-500 to-yellow-600/10"></div>
					<img src="{% static 'images/nirvana.jpg' %}" class="h-full w-full object-cover" />
				</div>
			</div>
		</a>
	</section>

	<section id="artists" class="mb-10">
		<h2 class="font-semibold mb-6">Artists Recommendations</h2>

		<div class="grid gap-6 grid-cols-2 sm:grid-cols-3 md:grid-cols-4 xl:grid-cols-5">
			{% for i in '0123456789'|make_list %}
				<a href="{% url 'artists:view' i %}">
					<div class="flex flex-col justify-end bg-gray-100 rounded-xl overflow-hidden p-4 text-gray-500">
						<div class="w-full h-full aspect-square mb-4 overflow-hidden rounded-lg bg-white flex items-center justify-center">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-8 w-8">
								<path d="M18 21a8 8 0 0 0-16 0" />
								<circle cx="10" cy="8" r="5" />
								<path d="M22 20c0-3.37-2-6.5-4-8a5 5 0 0 0-.45-8.3" />
							</svg>
						</div>

						<h3 class="text-sm font-semibold">Nirvana</h3>
						<p class="text-sm line-clamp-2">An American rock band formed in Aberdeen, Washington, in 1987.</p>
					</div>
				</a>
			{% endfor %}
		</div>
	</section>
{% endblock %}

templates/pages/artists/view.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block content %}
	<nav class="flex items-center justify-between mb-10">
		<div class="flex items-center space-x-2 text-sm text-gray-500">
			<a href="{% url 'app:dashboard' %}">Dashboard</a>
			<span>/</span>
			<a href="{% url 'artists:index' %}">Artists</a>
			<span>/</span>
			<a href="{% url 'artists:view' '1' %}" class="text-indigo-500">Nirvana</a>
		</div>

		{% include 'partials/profile.html' %}
	</nav>

	<section id="featured" class="mb-10">
		<div class="w-full aspect-[3/1] relative overflow-hidden rounded-xl mb-10">
			<img src="{% static 'images/nirvana.jpg' %}" class="h-full w-full object-cover" />
		</div>

		<div class="flex flex-col space-y-2">
			<span class="font-medium text-sm text-indigo-500 uppercase">Artists</span>
			<h1 class="text-5xl font-bold">Nirvana</h1>
			<p class="text-sm text-gray-500">Nirvana was an American rock band formed in Aberdeen, Washington, in 1987. Founded by lead singer and guitarist Kurt Cobain and bassist Krist Novoselic, the band went through a succession of drummers, most notably Chad Channing, before recruiting Dave Grohl in 1990.</p>
		</div>
	</section>

	<section id="songs" class="mb-10">
		<div class="flex items-center justify-between mb-4">
			<h2 class="font-semibold">Favorite Songs</h2>

			<div class="flex items-center space-x-4">
				<button class="w-10 h-10 rounded-full bg-indigo-500 flex items-center justify-center group" title="Play All" role="button">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 text-white">
						<polygon points="6 3 20 12 6 21 6 3" />
					</svg>
					<span class="sr-only">Play All</span>
				</button>
				<button class="w-10 h-10 rounded-full bg-indigo-500 flex items-center justify-center" title="Add to Playlist" role="button">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 text-white">
						<path d="M11 12H3" />
						<path d="M16 6H3" />
						<path d="M16 18H3" />
						<path d="M18 9v6" />
						<path d="M21 12h-6" />
					</svg>
					<span class="sr-only">Add to Playlist</span>
				</button>
			</div>
		</div>

		<div class="w-full overflow-hidden border border-gray-200 rounded-xl">
			<table class="w-full text-sm text-gray-500 border-collapse">
				<thead>
					<tr class="bg-gray-100 [&>th]:px-4 [&>th]:py-3 [&>th]:text-left [&>th]:font-semibold">
						<th class="text-start w-20">Actions</th>
						<th class="text-start w-auto">Title</th>
						<th class="text-start w-1/5">Duration</th>
						<th class="text-start w-1/5">Album</th>
					</tr>
				</thead>
				<tbody>
					{% for i in '01234'|make_list %}
						<tr class="bg-white [&>td]:px-4 [&>td]:py-3 border-t border-gray-200">
							<td>
								{% include 'partials/action.html' %}
							</td>
							<td>
								<h3 class="text-sm font-semibold">Smells Like Teen Spirit</h3>
								<p class="text-sm line-clamp-1">Nirvana most successful album, has sold more than 30 million copies worldwide, making it one of the best-selling albums ever.</p>
							</td>
							<td>3:45</td>
							<td>Nevermind</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</section>

	<section id="albums" class="mb-10">
		<h2 class="font-semibold mb-6">Latest Albums</h2>

		<div class="grid gap-6 grid-cols-2 sm:grid-cols-3 md:grid-cols-4 xl:grid-cols-5">
			{% for i in '01234'|make_list %}
				<a href="{% url 'albums:view' i %}">
					<div class="flex flex-col justify-end bg-gray-100 rounded-xl overflow-hidden p-4 text-gray-500">
						<div class="w-full h-full aspect-square mb-4 overflow-hidden rounded-lg bg-white flex items-center justify-center">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-8 w-8">
								<circle cx="12" cy="12" r="10" />
								<path d="M6 12c0-1.7.7-3.2 1.8-4.2" />
								<circle cx="12" cy="12" r="2" />
								<path d="M18 12c0 1.7-.7 3.2-1.8 4.2" />
							</svg>
						</div>

						<h3 class="text-sm font-semibold">Nevermind</h3>
						<p class="text-sm line-clamp-2">Nevermind, their most successful album, has sold more than 30 million copies worldwide, making it one of the best-selling albums ever.</p>
					</div>
				</a>
			{% endfor %}
		</div>
	</section>
{% endblock %}

templates/pages/playlists/create.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block content %}
	<nav class="flex items-center justify-between mb-10">
		<div class="flex items-center space-x-2 text-sm text-gray-500">
			<a href="{% url 'app:dashboard' %}">Dashboard</a>
			<span>/</span>
			<a href="{% url 'playlists:index' %}">Playlists</a>
			<span>/</span>
			<a href="{% url 'playlists:create' %}" class="text-indigo-500">Create</a>
		</div>

		{% include 'partials/profile.html' %}
	</nav>

	<section id="form" class="mb-10">
		<h2 class="font-semibold mb-4">Create Playlist</h2>

		<form action="#" method="post">
			<div class="mb-4">
				<label for="name" class="form-label">Name</label>
				<input type="text" name="name" id="name" class="form-input" />
			</div>

			<div class="mb-4">
				<label for="type" class="form-label">Playlist Type</label>
				<select name="type" id="type" class="form-input">
					<option value="private">Private</option>
					<option value="public">Public</option>
				</select>
			</div>

			<div class="mb-6">
				<label for="description" class="form-label">Description</label>
				<textarea name="description" id="description" class="form-input" rows="3"></textarea>
			</div>

			<div class="flex items-center space-x-4">
				<button type="submit" class="button">Create Playlist</button>
				<button type="reset" class="reset">Reset</button>
			</div>
		</form>
	</section>
{% endblock %}

templates/partials/sidebar.html
{% load static %}

<div class="flex flex-col space-y-10">
	<div class="px-4">
		<a href="{% url 'app:dashboard' %}">{% include 'partials/icon.html' %}</a>
	</div>

	<div class="w-full">
		<h2 class="px-4 font-semibold mb-2">Search</h2>

		<div class="relative">
			<input type="search" class="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:border-indigo-500 text-sm" placeholder="Keyword" />

			<a href="{% url 'app:search' %}">
				<button class="absolute inset-y-0 right-0 flex items-center pr-2">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 text-indigo-500">
						<circle cx="11" cy="11" r="8" />
						<path d="m21 21-4.3-4.3" />
					</svg>
				</button>
			</a>
		</div>
	</div>

	<div class="w-full">
		<h2 class="px-4 font-semibold mb-4">Charts</h2>
		<div class="flex flex-col space-y-2">
			<a href="{% url 'albums:index' %}">
				<div class="px-4 py-2 rounded-lg block w-full text-gray-500 hover:bg-gray-200 flex space-x-2 items-center">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5">
						<circle cx="12" cy="12" r="10" />
						<circle cx="12" cy="12" r="2" />
					</svg>
					<span class="text-sm">Albums</span>
				</div>
			</a>

			<a href="{% url 'artists:index' %}">
				<div class="px-4 py-2 rounded-lg block w-full text-gray-500 hover:bg-gray-200 flex space-x-2 items-center">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5">
						<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
						<circle cx="12" cy="7" r="4" />
					</svg>
					<span class="text-sm">Artists</span>
				</div>
			</a>

			<a href="{% url 'playlists:index' %}">
				<div class="px-4 py-2 rounded-lg block w-full text-gray-500 hover:bg-gray-200 flex space-x-2 items-center">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5">
						<path d="M3 14h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-7a9 9 0 0 1 18 0v7a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3" />
					</svg>
					<span class="text-sm">Playlists</span>
				</div>
			</a>

			<a href="{% url 'podcasts:index' %}">
				<div class="px-4 py-2 rounded-lg block w-full text-gray-500 hover:bg-gray-200 flex space-x-2 items-center">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5">
						<path d="m12 8-9.04 9.06a2.82 2.82 0 1 0 3.98 3.98L16 12" />
						<circle cx="17" cy="7" r="5" />
					</svg>
					<span class="text-sm">Podcasts</span>
				</div>
			</a>
		</div>
	</div>

	<div class="w-full">
		<div class="flex justify-between items-center mb-4">
			<h2 class="px-4 font-semibold">Playlists</h2>
			<a href="{% url 'playlists:create' %}">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 text-indigo-500">
					<path d="M5 12h14" />
					<path d="M12 5v14" />
				</svg>
			</a>
		</div>

		<div class="flex flex-col space-y-2">
			<a href="{% url 'playlists:view' '1' %}">
				<div class="px-4 py-2 rounded-lg block w-full text-gray-500 hover:bg-gray-200 flex space-x-2 items-center">
					<span class="text-sm">Favorites</span>
				</div>
			</a>

			<a href="{% url 'playlists:view' '2' %}">
				<div class="px-4 py-2 rounded-lg block w-full text-gray-500 hover:bg-gray-200 flex space-x-2 items-center">
					<span class="text-sm">My Playlists</span>
				</div>
			</a>

			<a href="{% url 'playlists:view' '3' %}">
				<div class="px-4 py-2 rounded-lg block w-full text-gray-500 hover:bg-gray-200 flex space-x-2 items-center">
					<span class="text-sm">New Releases</span>
				</div>
			</a>

			<a href="{% url 'playlists:view' '3' %}">
				<div class="px-4 py-2 rounded-lg block w-full text-gray-500 hover:bg-gray-200 flex space-x-2 items-center">
					<span class="text-sm">Downloads</span>
				</div>
			</a>
		</div>
	</div>
</div>

{% if request.path != '/player/' %}
	<a href="{% url 'app:player' %}">
		<div class="w-full bg-gray-100 p-4 rounded-lg">
			<div class="w-full aspect-square mb-4 rounded-lg overflow-hidden">
				<img src="{% static 'images/nirvana.jpg' %}" alt="nirvana" class="w-full h-full object-cover" />
			</div>

			<div class="flex items-center space-x-4">
				<button class="w-10 h-10 rounded-full overflow-hidden bg-indigo-500 flex items-center justify-center text-white">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 text-white animate-rotating">
						<circle cx="12" cy="12" r="10" />
						<path d="M6 12c0-1.7.7-3.2 1.8-4.2" />
						<circle cx="12" cy="12" r="2" />
						<path d="M18 12c0 1.7-.7 3.2-1.8 4.2" />
					</svg>
				</button>

				<div class="flex flex-col text-sm">
					<h5 class="font-semibold">Nirvana</h5>
					<p class="text-gray-500">All Apologies</p>
				</div>
			</div>
		</div>
	</a>
{% endif %}